version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - form_data:/data
    environment:
      - FLASK_APP=app/app.py
      - FLASK_ENV=development

volumes:
  form_data:
    driver: local
