version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /var/data:/data  # Mount a directory in the container to a path on Render's disk
    environment:
      - FLASK_APP=app/app.py
      - FLASK_ENV=development
